language: node_js
node_js:
  - 4.2.3
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - npm install -g bower grunt-cli
  - bower install
services: mysql
env:
  - NODE_ENV=travis
  - MYSQL_URI=mysql://travis:@127.0.0.1:3306/IOTDB_TEST
