language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 4.3.1
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
before_script:
  - npm install -g bower grunt-cli
  - bower install
  - "mysql -e 'create database if not exists IOTDB_TEST;'"
services: mysql
env:
  - NODE_ENV=travis
  - MYSQL_URI=mysql://travis:travis@127.0.0.1:3306/IOTDB_TEST
