language: node_js
cache:
  directories:
    - node_modules
    - client/bower_components
node_js:
  - 4.3.1
before_script:
  - npm install -g bower grunt-cli
  - bower install
  - "mysql -e 'create database if not exists IOTDB_TEST;'"
services: mysql
env:
  - MYSQL_URI=mysql://travis@127.0.0.1:3306/IOTDB_TEST
