language: node_js
cache:
  directories:
  - node_modules
  - client/bower_components
node_js:
- 4.3.1
before_script:
- npm install -g bower grunt-cli
- bower install
- mysql -e 'create database if not exists IOTDB_TEST;'
services: mysql
after_success:
  - coveralls
env:
  global:
  - NODE_ENV: travis
  - MYSQL_URI: mysql://travis@127.0.0.1:3306/IOTDB_TEST
notifications:
  slack:
    secure: fHSVlzSMhbsG0pXLiEASEze+s0++ZV/i1GROlTQRn6Qax7cGJu/DCat8snniyPrrWgP/4XdHN7OaV4SCtHYFZSaX/iYAzL29tDvYnH9CVpOiD6GtWH2/ObTWsZekrjvgnaAiGf41Y6ceg6pATdpsfugFj5Nu220AF6OUa+RFV3OBBW92b/SXFE1D0A2XEMPWwKs2L/TLZYLWPIRJXzqFOWyO5BQGZqu6K/nrUccc2ZTZ4PZkTtHQ9l4/UvKLQA60A4BYuMcbW9wu1a4z6oKyPqgVReNbL/75oOtOth4W5VOLXk8yrqPFTGh3jpoyev80CYAqkNS0jvW3mOoqwbat6GYCS5sV9dQmN6rJ/UDH1WvKJY9FWWbGIZNLMHpDob3SWL9/Ms77/SpK3y2VU/ExXphJnQ6sZAarChOl1VtHVJJej4Ak7S0BopNOhcXaIRqItrDHGXb8J8zdYzUV0kO4XyS0/Ai0fUnZmMiMtwqya1ouLtM3qRGpET8aIA267BYTIgsje8yP9g4IZxnHeizIQKhI7nLNBDgwCA/1Rt4m7oVcPhbeM3AyxKUprZ7iElTu2nEYbfl6/BnscLguWMnib+VymzWXVFFojTTZSkgbFaqYG9Qr51EMbzUsoZQXuiy8XyAfS8/jhUhoG3B+l7uHb7c60LzQxDrcxDf5LvaQqzE=
before_deploy: test $TRAVIS_TEST_RESULT = 0 && grunt build && cd dist && npm install --prod && cd $TRAVIS_BUILD_DIR && tar -zcvf meccano-webconsole-$TRAVIS_TAG.tar.gz dist
deploy:
  provider: releases
  file: meccano-webconsole-$TRAVIS_TAG.tar.gz
  on:
    tags: true
  api-key:
    secure: RUkJmY14tMpk/3npqbAYNowm7R0dbuRGHCfMmXKuZHj+6i0WBDRZLTZEn4MmLv1wpl1f/qOg35eDVJnXOahELfb/TbBDhnAb/uUIvgWJ4BqDzOQ6ibI9DjH6vPNjsBXt2dO/3wli8hPTN5GGSyaJl/M1foxEHDicW7SvoOBKnCorFfAF9nJSv8Sqj2hAC8JDM4VfNuiLaIqnpr1nB0WznWjQEg/8jj8YPCsMJggBHk7wJas8GRymtkC9FcnUkrwX6cFlowqqEnc1WfXADWTG9pdqehFS5EtYk1jqL8Xt82wTInaQJoJ1bVBHHdx/6bhtwSZAbcjlhajKU+YZFA2lD5lSGlpLMnDbDDJbROwjULKkuXh3NNTL8IeaJiBOjy5GQGhO0czyAbXvap1JL/Nj5F4J9+j+R8C2AsYFx6RdxeKzSulLIm84FRPu+B4EDMKSpXUoL+y6X71LoCVHkeyx2M7yE0rWVxqAvj0fqD+pLB/wEDIWtYFKXNJJ0M2XnkUPexaobWcdZh3xROBsOcw9SbJoZl3iJSMKYdteCMxpnt/Dl/C6/n1xc01SCXRcFXQo4NhUkL6sSONz86zX0FIMosN7evI8hHJzsWoHUL9VnyMEsPSZE4QChNMC804kVllnz0kaq1+huwJZfIs3EgpaOWfy5qSi0rBg3MNIshXq5io=
